### ISSUE TITLE
Will this actually last?

### ISSUE THREAD

**Issue by eliapplethetech** [FiberZen/FiberZen.github.io#1]
Will this die quickly? I'd call that an issue.

**Comment by MooShoe** [comment]
this isnt a real issue eli

**Comment by ModernFeelGames** [comment]
Please take Fiber Zen seriously, and we don't know if it will be a thing actully, we haven't announced anything on scratch yet because if we do, we want it to be final that zen will happen all the way! Thank you for your concern!

**Comment by iiLucky** [comment]
Fiber Zen is being managed by me and we are making it totally different from Nova. We really won't be relying on the cloud much. So far, we have been making good progress since the school year is closing and we can do more work over the summer break. We have also decided not to tell the public on Scratch about Fiber Zen until we at least have it almost complete. I have gotten most of the Nova team with me and a few others from Beta MooShoe invited. I know for sure that we can correct what we did in Nova by making Zen. It may be a failure but it is best to try to finish what we started.

**Comment by MooShoe** [comment]
chill dudes

**Comment by eliapplethetech** [comment]
ok. i want to help but no slack or discord. maybe dropbox or something?

**Comment by ModernFeelGames** [comment]
Mooshoe, please join the fiber zen chat room again, you haven't been on discord!

**Comment by MooShoe** [comment]
lets use nextcloud.com for file sharing and stuff because FOSS for the win and eli could join us

**Comment by ModernFeelGames** [comment]
Ok

**Comment by ModernFeelGames** [comment]
Do you want to create the room and invite me and I'll invite the rest of the discord server

**Comment by ModernFeelGames** [comment]
Wait, nvm. I want solid slack or discord. Maybe skype.

**Comment by ModernFeelGames** [comment]
Wait, nvm. I want solid slack or discord. Maybe skype.

**Comment by MooShoe** [comment]
its for file sharing like dropbox just google it

**Comment by ModernFeelGames** [comment]
Ik, but if we are switching from discord or slack just to file share, that would be stupid. I would like to be able to talk with the other devs. File sharing comes with slack and discord anyway.

**Comment by ModernFeelGames** [comment]
Also, everyone is waiting for you to be on discord, youve been mentioned and DMd like 80 billion times!

**Comment by MooShoe** [comment]
drama alert

**Comment by ModernFeelGames** [comment]
eww, no.

**Comment by MooShoe** [comment]
ok i will be on soon
